# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pomodoro.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.setWindowModality(QtCore.Qt.NonModal)
        main_window.resize(400, 445)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(main_window.sizePolicy().hasHeightForWidth())
        main_window.setSizePolicy(sizePolicy)
        main_window.setMinimumSize(QtCore.QSize(300, 400))
        main_window.setMaximumSize(QtCore.QSize(600, 800))
        main_window.setLayoutDirection(QtCore.Qt.LeftToRight)
        main_window.setAutoFillBackground(False)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(main_window)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(main_window)
        self.groupBox.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.spinBox_work_hours = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_work_hours.setObjectName("spinBox_work_hours")
        self.horizontalLayout_3.addWidget(self.spinBox_work_hours)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.spinBox_work_minutes = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_work_minutes.setObjectName("spinBox_work_minutes")
        self.horizontalLayout_3.addWidget(self.spinBox_work_minutes)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.spinBox_work_seconds = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_work_seconds.setObjectName("spinBox_work_seconds")
        self.horizontalLayout_3.addWidget(self.spinBox_work_seconds)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(main_window)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.spinBox_break_hours = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_break_hours.setObjectName("spinBox_break_hours")
        self.horizontalLayout_4.addWidget(self.spinBox_break_hours)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.spinBox_break_minutes = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_break_minutes.setObjectName("spinBox_break_minutes")
        self.horizontalLayout_4.addWidget(self.spinBox_break_minutes)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.spinBox_break_seconds = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_break_seconds.setObjectName("spinBox_break_seconds")
        self.horizontalLayout_4.addWidget(self.spinBox_break_seconds)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(main_window)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.spinBox_repetitions = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_repetitions.setObjectName("spinBox_repetitions")
        self.horizontalLayout.addWidget(self.spinBox_repetitions)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.frame_2 = QtWidgets.QFrame(main_window)
        self.frame_2.setAutoFillBackground(False)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout.addWidget(self.frame_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_clock = QtWidgets.QLabel(main_window)
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif")
        font.setPointSize(36)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_clock.setFont(font)
        self.label_clock.setAutoFillBackground(False)
        self.label_clock.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.label_clock.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_clock.setTextFormat(QtCore.Qt.PlainText)
        self.label_clock.setScaledContents(True)
        self.label_clock.setAlignment(QtCore.Qt.AlignCenter)
        self.label_clock.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_clock.setObjectName("label_clock")
        self.verticalLayout_5.addWidget(self.label_clock)
        self.verticalLayout_2.addLayout(self.verticalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_start = QtWidgets.QPushButton(main_window)
        self.pushButton_start.setObjectName("pushButton_start")
        self.horizontalLayout_2.addWidget(self.pushButton_start)
        self.pushButton_pause = QtWidgets.QPushButton(main_window)
        self.pushButton_pause.setEnabled(False)
        self.pushButton_pause.setObjectName("pushButton_pause")
        self.horizontalLayout_2.addWidget(self.pushButton_pause)
        self.pushButton_stop = QtWidgets.QPushButton(main_window)
        self.pushButton_stop.setEnabled(False)
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.horizontalLayout_2.addWidget(self.pushButton_stop)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "Pomodoro"))
        self.groupBox.setTitle(_translate("main_window", "Work Time"))
        self.label_2.setText(_translate("main_window", "Hours:"))
        self.label_3.setText(_translate("main_window", "Minutes:"))
        self.label.setText(_translate("main_window", "Seconds:"))
        self.groupBox_2.setTitle(_translate("main_window", "Break Time"))
        self.label_5.setText(_translate("main_window", "Hours:"))
        self.label_6.setText(_translate("main_window", "Minutes:"))
        self.label_4.setText(_translate("main_window", "Seconds:"))
        self.label_8.setText(_translate("main_window", "Repetitions:"))
        self.label_clock.setText(_translate("main_window", "00:00:00"))
        self.pushButton_start.setText(_translate("main_window", "Start"))
        self.pushButton_pause.setText(_translate("main_window", "Pause"))
        self.pushButton_stop.setText(_translate("main_window", "Stop"))

