# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pomodoro.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName(_fromUtf8("main_window"))
        main_window.setWindowModality(QtCore.Qt.NonModal)
        main_window.resize(390, 469)
        main_window.setLayoutDirection(QtCore.Qt.LeftToRight)
        main_window.setAutoFillBackground(False)
        self.verticalLayout_3 = QtGui.QVBoxLayout(main_window)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(main_window)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.spinBox_work_hours = QtGui.QSpinBox(self.groupBox)
        self.spinBox_work_hours.setObjectName(_fromUtf8("spinBox_work_hours"))
        self.horizontalLayout_3.addWidget(self.spinBox_work_hours)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.spinBox_work_minutes = QtGui.QSpinBox(self.groupBox)
        self.spinBox_work_minutes.setObjectName(_fromUtf8("spinBox_work_minutes"))
        self.horizontalLayout_3.addWidget(self.spinBox_work_minutes)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.spinBox_work_seconds = QtGui.QSpinBox(self.groupBox)
        self.spinBox_work_seconds.setObjectName(_fromUtf8("spinBox_work_seconds"))
        self.horizontalLayout_3.addWidget(self.spinBox_work_seconds)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(main_window)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_4.addWidget(self.label_5)
        self.spinBox_break_hours = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox_break_hours.setObjectName(_fromUtf8("spinBox_break_hours"))
        self.horizontalLayout_4.addWidget(self.spinBox_break_hours)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_4.addWidget(self.label_6)
        self.spinBox_break_minutes = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox_break_minutes.setObjectName(_fromUtf8("spinBox_break_minutes"))
        self.horizontalLayout_4.addWidget(self.spinBox_break_minutes)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.spinBox_break_seconds = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox_break_seconds.setObjectName(_fromUtf8("spinBox_break_seconds"))
        self.horizontalLayout_4.addWidget(self.spinBox_break_seconds)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.frame_2 = QtGui.QFrame(main_window)
        self.frame_2.setAutoFillBackground(False)
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_2.setLineWidth(0)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_8 = QtGui.QLabel(self.frame_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout.addWidget(self.label_8)
        self.spinBox_repetitions = QtGui.QSpinBox(self.frame_2)
        self.spinBox_repetitions.setObjectName(_fromUtf8("spinBox_repetitions"))
        self.horizontalLayout.addWidget(self.spinBox_repetitions)
        self.horizontalLayout_9.addLayout(self.horizontalLayout)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.frame_2)
        self.groupBox_3 = QtGui.QGroupBox(main_window)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_clock = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.label_clock.setFont(font)
        self.label_clock.setTextFormat(QtCore.Qt.PlainText)
        self.label_clock.setScaledContents(True)
        self.label_clock.setAlignment(QtCore.Qt.AlignCenter)
        self.label_clock.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_clock.setObjectName(_fromUtf8("label_clock"))
        self.horizontalLayout_7.addWidget(self.label_clock)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_7)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButton_start = QtGui.QPushButton(main_window)
        self.pushButton_start.setObjectName(_fromUtf8("pushButton_start"))
        self.horizontalLayout_2.addWidget(self.pushButton_start)
        self.pushButton_pause = QtGui.QPushButton(main_window)
        self.pushButton_pause.setEnabled(False)
        self.pushButton_pause.setObjectName(_fromUtf8("pushButton_pause"))
        self.horizontalLayout_2.addWidget(self.pushButton_pause)
        self.pushButton_stop = QtGui.QPushButton(main_window)
        self.pushButton_stop.setEnabled(False)
        self.pushButton_stop.setObjectName(_fromUtf8("pushButton_stop"))
        self.horizontalLayout_2.addWidget(self.pushButton_stop)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        main_window.setWindowTitle(_translate("main_window", "Pomodoro", None))
        self.groupBox.setTitle(_translate("main_window", "Work Time", None))
        self.label_2.setText(_translate("main_window", "Hours:", None))
        self.label_3.setText(_translate("main_window", "Minutes:", None))
        self.label.setText(_translate("main_window", "Seconds:", None))
        self.groupBox_2.setTitle(_translate("main_window", "Break Time", None))
        self.label_5.setText(_translate("main_window", "Hours:", None))
        self.label_6.setText(_translate("main_window", "Minutes:", None))
        self.label_4.setText(_translate("main_window", "Seconds:", None))
        self.label_8.setText(_translate("main_window", "Repetitions:", None))
        self.groupBox_3.setTitle(_translate("main_window", "Timer", None))
        self.label_clock.setText(_translate("main_window", "00:00:00", None))
        self.pushButton_start.setText(_translate("main_window", "Start", None))
        self.pushButton_pause.setText(_translate("main_window", "Pause", None))
        self.pushButton_stop.setText(_translate("main_window", "Stop", None))

